"""empty message

Revision ID: 3e50fb4bbd69
Revises: eb641325aa5d
Create Date: 2021-01-25 14:02:10.377770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e50fb4bbd69'
down_revision = 'eb641325aa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###
