"""empty message

Revision ID: eb641325aa5d
Revises: a98e2ae15892
Create Date: 2021-01-25 13:25:43.044216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb641325aa5d'
down_revision = 'a98e2ae15892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('additionalReq', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('endDate', sa.Date(), nullable=True))
    op.add_column('bookings', sa.Column('numGuests', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('totalPrice', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'totalPrice')
    op.drop_column('bookings', 'numGuests')
    op.drop_column('bookings', 'endDate')
    op.drop_column('bookings', 'additionalReq')
    # ### end Alembic commands ###
