"""empty message

Revision ID: 3464f3f0a26d
Revises: 3e50fb4bbd69
Create Date: 2021-01-25 14:02:25.316681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3464f3f0a26d'
down_revision = '3e50fb4bbd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
